### ISSUE TITLE
In 0.26, sessions are saved too late

### ISSUE THREAD

**Issue by dakkar** [stevan/plack-middleware-session#29]
In 0.26, the Session is stored during the cleanup phase. I understand that this is necessary in cases where the application returns a streaming response and it may well be modifying session data after the initial return. It does create a problem, though: there's now a race condition between the server and the client, in the case of pre-forking / non-blocking servers. This is what happens:

* the client requests `/foo`
* the application on server process 1 stores data in the session, and *redirects* to `/bar`
* the client sees the 302 and `Location` header, and requests `/bar`
* server process 1 is saving the session
* server process 2 answer the request to `/bar`, and loads *the previous version of the session*
* bad things happen

Could we save the session twice, once directly in the response callback (like 0.25 did), and then in cleanup?

**Comment by dakkar** [comment]
https://gist.github.com/dakkar/5645bb54bdfa1ede08fa a small test case.

The problem does not seem to happen much with the `File` store, but it happen pretty reliably with the `DBI` store.

**Comment by miyagawa** [comment]
Excellent catch. cc @alexmv 

We'd either have an option to disable the behavior, or have some kind of API using special keys in `$env` to change the behavior in runtime - which would probably default to the *before* phase like we do, since updating session in the stream response sounds rarer for me.

Doing the save twice sounds safe but I personally don't like it.

**Comment by miyagawa** [comment]
`psgix.session.options` already has similar `no_store` which prevents updating the data for the session that doesn't need save. Can we add a new option like `late_store` which enables the introduced behavior, and otherwise updating before the streaming response like previously? @alexmv

**Comment by alexmv** [comment]
Hm.  I entirely believe the race condition -- though I'm unable to duplicate it using the gist you showed.  Is the `got/expected` failure supposed to occur without the ForceSessionSave middlware?  Even with 10 parallel user agents and upping it to 5 redirects instead of three, I'm unable to get a mismatch.

I'll push a branch shortly which makes the late storage behavior contingent on a `psgix.sesison.options` flag.

**Comment by alexmv** [comment]
@dakkar, can you confirm the above branch fixes this for you?

**Comment by miyagawa** [comment]
I just shipped 0.27-TRIAL with the fix.

**Comment by dakkar** [comment]
@alexmv confirmed, it works. thank you!
